--[sqlplus at cmd, login as scott/tiger]
--CREATE USER sam IDENTIFIED BY tiger;
--GRANT connect, resource TO sam;

--insert into customer(cno) values(1);
--INSERT INTO PRODUCT(PNO) VALUES(2);
--INSERT INTO PRODUCT(PNO) VALUES(3);
--Insert into LIST_ORDER(cno,PNO,ocnt) values(1,2,22);
--Insert into LIST_ORDER(cno,PNO,ocnt) values(1,3,33); --BAG identified by cno
--insert into FINISHED_ORDER(lono,cno) values(11,1); --to have ORDERS LIST
--select * from List_order where cno = 1; -- what customer has in her BAG
--INSERT INTO ORDERS(ONO,LONO, PNO) VALUES(111, 11,2); --move from BAG to ORDERS
--INSERT INTO ORDERS(ONO,LONO, PNO,ocnt) VALUES(112, 11,3,33);
--delete from LIST_ORDER where cno = 1;--delete bag
--select * from Finished_order;
--select pno, ocnt from orders where lono = (select lono from finished_order where cno = 1);

DROP TABLE CUSTOMER;
DROP TABLE QUESTION;
DROP TABLE ANSWER;
DROP TABLE PRODUCT;
DROP TABLE LIST_ORDER;
DROP TABLE FINISHED_ORDER;
DROP TABLE ORDERS;

CREATE TABLE MANAGER(
MNO NUMBER PRIMARY KEY,
NAME VARCHAR2(100),
GENDER VARCHAR(20),
ID VARCHAR2(100),
PW VARCHAR2(100),
TEL VARCHAR2(100),
EMAIL VARCHAR2(100),
ADDR VARCHAR2(4000)
);
CREATE SEQUENCE manager_seq increment by 1 start with 1;

CREATE TABLE CUSTOMER(
CNO NUMBER PRIMARY KEY,
NAME VARCHAR2(100),
GENDER VARCHAR(20),
ID VARCHAR2(100),
PW VARCHAR2(100),
TEL VARCHAR2(100),
EMAIL VARCHAR2(100),
ADDR VARCHAR2(4000)
);

CREATE SEQUENCE customer_seq increment by 1 start with 1;

CREATE TABLE QUESTION(
QNO NUMBER PRIMARY KEY,
CNO NUMBER,
QNAME VARCHAR2(1000),
QMESSAGE VARCHAR2(4000),
REGDATE DATE,
CONSTRAINT FK_QUESTION_CNO FOREIGN KEY(CNO) REFERENCES CUSTOMER(CNO)
);
CREATE SEQUENCE question_seq increment by 1 start with 1;

CREATE TABLE ANSWER(
QNO NUMBER,
MNO NUMBER,
CNO NUMBER,
AMESSAGE VARCHAR2(4000),
CONSTRAINT FK_ANSWER_QNO FOREIGN KEY(QNO) REFERENCES QUESTION(QNO)
);

CREATE TABLE PRODUCT(
PNO NUMBER PRIMARY KEY,
IMG VARCHAR2(1000),
PNAME VARCHAR2(1000),
PRICE NUMBER,
DESCRIPTION VARCHAR2(4000),
STOCK NUMBER,
TYPE VARCHAR2(30) CHECK (TYPE IN('capsule','dripbag','beans','extraction','cup','grinder'))
);

CREATE SEQUENCE product_seq increment by 1 start with 1;
CREATE SEQUENCE product2_seq increment by 1 start with 100000;

CREATE TABLE LIST_ORDER(
CNO NUMBER,
PNO NUMBER,
OCNT NUMBER,
CONSTRAINT FK_LIST_ORDER_CNO FOREIGN KEY(CNO) REFERENCES CUSTOMER(CNO),
CONSTRAINT FK_LIST_ORDER_PNO FOREIGN KEY(PNO) REFERENCES PRODUCT(PNO)
);

CREATE TABLE FINISHED_ORDER(
LONO NUMBER PRIMARY KEY,
CNO NUMBER,
ODRDATE DATE,
ADDR VARCHAR2(4000),
CONSTRAINT FK_FINISHED_ORDER_CNO FOREIGN KEY(CNO) REFERENCES CUSTOMER(CNO)
);

CREATE SEQUENCE finished_order_seq increment by 1 start with 1;

CREATE TABLE ORDERS(
ONO NUMBER PRIMARY KEY,
LONO NUMBER,
PNO NUMBER,
OCNT NUMBER,
CONSTRAINT FK_ORDER_LONO FOREIGN KEY(LONO) REFERENCES FINISHED_ORDER(LONO),
CONSTRAINT FK_ORDER_PNO FOREIGN KEY(PNO) REFERENCES PRODUCT(PNO)
);

CREATE SEQUENCE orders_seq increment by 1 start with 1;